// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using prj.data;

#nullable disable

namespace prj.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230911174857_simulador3")]
    partial class simulador3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("prj.Models.EmprestimoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ch")
                        .HasColumnType("int");

                    b.Property<int>("comporativo")
                        .HasColumnType("int");

                    b.Property<int>("rhideal")
                        .HasColumnType("int");

                    b.Property<int>("rhreal")
                        .HasColumnType("int");

                    b.Property<string>("setor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Emprestimo");
                });

            modelBuilder.Entity("prj.Models.SimuladorModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ala")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("carga")
                        .HasColumnType("int");

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dimensionamento")
                        .HasColumnType("int");

                    b.Property<int>("equipemin")
                        .HasColumnType("int");

                    b.Property<string>("escala")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("leitos")
                        .HasColumnType("int");

                    b.Property<int>("rhminimo")
                        .HasColumnType("int");

                    b.Property<int>("rhminimoturno")
                        .HasColumnType("int");

                    b.Property<int>("salas")
                        .HasColumnType("int");

                    b.Property<string>("setor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Simulador");
                });
#pragma warning restore 612, 618
        }
    }
}
